[tool.poetry]
name = "todo-cli"
version = "0.1.0"
description = ""
authors = ["iRaySpace <irayspacii@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.3"
uuid = "^1.30"
prettytable = "^3.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
