[tool.poetry]
name = "video-creator"
version = "0.1.0"
description = ""
authors = ["irayspace <irayspacii@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
moviepy = "^2.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
